### ISSUE TITLE
It would have been easier to install with demo sql | roles errors

### ISSUE THREAD

**Issue by hitmc** [yolanmees/postier#6]
Hi,

I followed the instructions. I am getting There is no role named `admin` error.

Guide me

**Comment by quantumio** [comment]
> 
> 
> Hi,
> 
> I followed the instructions. I am getting There is no role named `admin` error.
> 
> Guide me


Shame, I'm getting the same error - looks like a good lil repo.  
Artisan Seed and or migrate don't really do much ...or is there a SuperAdmin login/creation in the CLI?

Also then "npm run dev" is a little out of sequence from the instructions...minor point

Any chance of some of help on this please Postier? :-/

**Comment by yolanmees** [comment]
Hi,

The repo is outdated and actually poorly maintained. I will try to make asap a working update. Hope people still want to help me work out the current version.

Which feature would you like to use Postier for? So i can make sure that one is working in the update (eta: +1 day)

**Comment by yolanmees** [comment]
There is a new branch "Fix-admin-issue". When this fix is verified I will merge it with the master branch.

**Comment by quantumio** [comment]
awesome!

and yes I personally would really appreciate that.  I'll be watching the
repo with anticipation :-)

Do you have plans for laravel 6x ?
cheers
Dave

**Comment by yolanmees** [comment]
The update should work now, mind that u know have to execute 'php artisan db:seed'.
Which feature would you like to use Postier for? 

I'll check if all libraries are working with laravel 6.

**Comment by quantumio** [comment]
Cool, im about to spin up in the localhost -

The features...humm, i was hoping most would work (to a basic level) but im also looking to contribute.  I've friended you on FB, would really like a chat when you have some time.

Appreciate the effort today, cheers
Dave

**Comment by yolanmees** [comment]
I did accept the invite, I close the issue now

**Comment by quantumio** [comment]
cool, so yeah you can close it now - register blade sorts superadmin for now ;-)
Cheers again.
